### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by MrTurtles** [1Computer1/megumin-selfbot#10]
[2018-01-03 01:01:24]: [Error]: TypeError: util.promisify is not a function
    at Object.<anonymous> (C:\Users\Dave\Documents\megumin-selfbot-master\src\co
mmands\data\image.js:10:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at CommandHandler.load (C:\Users\MYNAME\Documents\megumin-selfbot-master\node_
modules\discord-akairo\src\struct\AkairoHandler.js:145:46)
    at CommandHandler.loadAll (C:\Users\MYNAME\Documents\megumin-selfbot-master\no
de_modules\discord-akairo\src\struct\AkairoHandler.js:174:48)

**Comment by 1Computer1** [comment]
Update to Node 8+
