### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by SneakySnake04** [1Computer1/megumin-selfbot#5]
I have no idea why, but this always comes up in the Command prompt when I open Megumin 

SyntaxError: C:\Users\imagu\megumin\src\data\config.json: Unexpected token O in
JSON at position 18
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\imagu\megumin\megumin.js:4:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)

need help too...

**Comment by 1Computer1** [comment]
Could you show me the contents of config.json?

**Comment by SneakySnake04** [comment]
It's fixed now. But something was going on that I didn't understand at that time. I don't think I can even get the previous config.json file back. So....shit.
